theme = "gruvbox_light"

[editor]
auto-save = true
cursorline = true
line-number = "relative"
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true

[keys.insert]
home = "normal_mode"
